Phase01
Star-Academy/Summer1401-FE-Team06 pull request #1
Opened 2022-07-20 12:23 UTC by AliZoghi

2022-07-20 13:15 UTC, milar7 requested changes
واسه اکثر فایل‌ها از prettier استفاده نکردید. یبار واسه همش اجرا کنید.

2022-07-20 13:29 UTC, milar7 commented on README.md
> +To get more help on the Angular CLI use `ng help` or go check out the [Angular CLI Overview and Command Reference](https://angular.io/cli) page.
قابل قبول نیست
فارسی باشه
اسم سایت
توضیح کامل در مورد پروژه و کارهایی که انجام میده
توضیح در مورد فیچرهای فعلی و فیچرهایی که در آینده میخواید اضافه کنید 
مشخصات توسعه دهندگان

2022-07-24 08:09 UTC, HessamCheraghi commented on src/app/app.component.spec.ts
> +// });
یه فایل spec فعلا دست نزنید اینها نباید کامنت باشه  {1}

2022-07-24 08:14 UTC, HessamCheraghi commented on src/app/components/banner/banner.component.html
> +            <a>محصولات بیشتر</a>
اینجا برای تگ a حتما یه `routerLink="/"` بزارید خالی نمونه همچنین به فایل ماژول هم `RouterModule` اضافه کنید که ارور نده. {2}

2022-07-24 08:16 UTC, SinaMAmini commented on src/app/components/slider-card/slider-card.component.scss
> +    box-shadow: 18px 14px 23px hsla(0, 0%, 0%, 0.25);
px -> rem

2022-07-24 08:17 UTC, SinaMAmini commented on src/app/components/slidebar/slidebar.component.scss
> +    font-size: 18px;
باید rem باشه

2022-07-24 08:18 UTC, SinaMAmini commented on src/app/components/main-cards/sample-data.ts
> +    {oldPrice: '25000', newPrice: '14000', imageUrl: 'assets/images/card9.avif'},
پسوند webp بیشتر برای سایت توصیه میشه

2022-07-24 08:19 UTC, SinaMAmini commented on src/app/components/icon/icon.component.scss
> +        height: 24px;
pxنباید باشه

2022-07-24 08:20 UTC, SinaMAmini commented on src/app/components/icon/icon.component.scss
> +        height: 20px;
rem

2022-07-24 08:20 UTC, HessamCheraghi commented on src/styles.scss
> +body {
این جا به `html` یه فونت سایز `62.5%` بده تا هر 1rem برابر 10px باشه و نخوای اندازه های اعشاری بدی {3}

2022-07-24 08:22 UTC, HessamCheraghi commented on src/app/components/banner/banner.component.scss
> +    padding: 0.8125rem;
گفتم {3}

2022-07-24 08:24 UTC, SinaMAmini commented on src/app/components/slider-card/slider-card.component.html
> +        <img src="assets/images/Witcher.jpg" alt="بازی the witcher" />
فرمت webp بهتره

2022-07-24 08:24 UTC, SinaMAmini commented on src/app/components/header/components/hero/game-slider/game-slider.component.html
> +    <img src="assets/images/Witcher.jpg" alt="بازی" />
webp

2022-07-24 08:25 UTC, HessamCheraghi commented on src/app/components/banner/banner.component.ts
> +    @Input() public bgColor: string = '';
فکر کنم این اضافی باشه {4}

2022-07-24 08:26 UTC, SinaMAmini commented on src/app/components/banner/banner.component.html
> +        <img src="assets/images/banner.jpg" alt="بنر بزرگ" />
webp

2022-07-24 08:26 UTC, HessamCheraghi commented on src/app/components/banner/banner.component.html
> +<div [class]="bgColor" class="banner section">
اینجا هم از تایپ اسکریپت مقداری نمیگیره {4}

2022-07-24 08:28 UTC, SinaMAmini requested changes
کد خوبی بود
مشکلات را نوشتم

2022-07-24 08:30 UTC, HessamCheraghi commented on src/app/components/footer/footer.component.html
> +        <span>Copyright © 2022 seeto.ir</span>
اینجا به جای علامت کپی رایت از این استفاده کنید 
```
&copy;
```
{5}

2022-07-24 08:31 UTC, HessamCheraghi commented on src/app/components/footer/footer.component.html
> +            <i class="fa-brands fa-youtube"></i>
اگه این ها قراره لینک باشه یه تگ a  دورشون بزار و چون لینک به بیرونه `href="#"` بذارید. {6}

2022-07-24 08:32 UTC, HessamCheraghi commented on src/app/components/footer/footer.component.scss
> +    padding: 0 0.125rem;
گفتم {3}

2022-07-24 08:33 UTC, HessamCheraghi commented on src/app/components/footer/footer.component.ts
> +    ngOnInit(): void {}
اینا هم حذف بشه {7}

2022-07-24 08:35 UTC, HessamCheraghi commented on src/app/components/header/components/search-box/search-box.component.scss
> +        font-size: 1.125rem;
گفتم {3}

2022-07-24 08:37 UTC, HessamCheraghi commented on src/app/components/header/components/second-navbar/second-navbar.component.html
> +            <li><a href="#">پشتیبانی</a></li>
گفتم {2}

2022-07-24 08:37 UTC, HessamCheraghi commented on src/app/components/header/components/second-navbar/second-navbar.component.html
> +                <a href="#">ثبت نام</a>
گفتم {2}

2022-07-24 08:40 UTC, HessamCheraghi commented on src/app/components/icon/icon.component.scss
> +        height: 24px;
به جای px از rem  استفاده کنید {8}

2022-07-24 08:41 UTC, HessamCheraghi commented on src/app/components/main-cards/main-cards.component.scss
> +    //grid-template-columns: auto auto auto;
کامنت پاک بشه

2022-07-24 08:43 UTC, HessamCheraghi commented on src/app/components/main/components/slider-section/slider-section.component.spec.ts
> +// });
گفتم {1}

2022-07-24 08:44 UTC, HessamCheraghi commented on src/app/components/primary-title/primary-title.component.ts
> +    @Input() public title: string = '';
حذف بشه

2022-07-24 08:44 UTC, HessamCheraghi commented on src/app/components/slider-card/slider-card.component.scss
> +    box-shadow: 18px 14px 23px hsla(0, 0%, 0%, 0.25);
به جای px  از rem  استفاده کنید

2022-07-24 08:46 UTC, HessamCheraghi requested changes
کارتون عالیه چند تا ایراد بود گذاشتم

2022-07-24 09:26 UTC, SinaMAmini approved these changes

2022-07-24 09:26 UTC, HessamCheraghi approved these changes

2022-07-24 09:52 UTC, dibaaamir requested changes

2022-07-24 09:52 UTC, dibaaamir commented on src/styles.scss
> +@import url('https://cdn.jsdelivr.net/gh/rastikerdar/shabnam-font@v5.0.1/dist/font-face.css');
به جای ایمپورت توی فایل اچ تی ام ال لینک بزارید. کند میکنه صفحه رو

2022-07-24 09:52 UTC, dibaaamir commented on src/styles.scss
> +    --primary-font: 'Shabnam', sans-serif;
برای کل اچ تی ام ال بزارین به جای اینجا

2022-07-24 09:52 UTC, dibaaamir commented on src/app/components/footer/footer.component.scss
> +    font-family: 'Shabnam', sans-serif;
وقتی برای کل اچ تی ام توی style.scss بزارین دیگه نیازی به اینجا نیست

2022-07-24 09:52 UTC, dibaaamir commented on src/app/components/header/components/search-box/search-box.component.scss
> +    --input-color: hsla(36, 100%, 50%, 0.3);
به نظرم اگر یه رنگ روشن تر بزارین بهتر باشه

2022-07-24 09:52 UTC, dibaaamir commented on src/app/components/header/components/search-box/search-box.component.scss
> +            font-style: var(--primary-font);
اینجا این کار نکرده. به نظرم ببریدش توی style.scss و برای تمام اینپوت ها بزارید این فونت رو و از font-family باید استفاده کنین

2022-07-24 09:52 UTC, dibaaamir commented on src/app/components/header/components/second-navbar/second-navbar.component.scss
> +                    transition: color 0.3s ease;
از transition استفاده نکنین برای رنگ.

2022-07-24 09:52 UTC, dibaaamir commented on src/app/components/header/components/second-navbar/second-navbar.component.scss
> +            transition: color 0.3s ease;
نباید از ترنزیشن استفاده کرد

2022-07-24 09:52 UTC, dibaaamir commented on src/app/components/header/components/second-navbar/second-navbar.component.scss
> +                    transition: color 0.3s ease;
کلا همه جا ممنوعه بردارین

2022-07-24 10:24 UTC, dibaaamir approved these changes

2022-07-24 11:03 UTC, milar7 requested changes
چون از Stylelint استفاده نکردین فرمت فایل های scss تون درست نیست. نصبش کنید

2022-07-24 11:03 UTC, milar7 commented on src/app/components/slider-card/slider-card.component.scss
> +        left: 0;
inset-block-top
inset-inline-start

2022-07-24 11:03 UTC, milar7 commented on src/app/components/slider-card/slider-card.component.spec.ts
> +// import { ComponentFixture, TestBed } from '@angular/core/testing';
این چرا کامنته؟

2022-07-24 12:03 UTC, milar7 approved these changes

2022-07-24 12:07 UTC, AtaReversei reviewed
خسته نباشید

2022-07-24 12:07 UTC, AtaReversei commented on src/app/components/more-button/more-button.component.html
> +    <span>بیشتر </span>
یدونه فاصله اضافی هست اینجا شاید بعدا تو استایل وسط چین کردن اینا به مشکل بخورید که کاملا وسط وسط نشه

2022-07-24 12:07 UTC, AtaReversei commented on src/app/components/primary-title/primary-title.component.scss
> +    margin-bottom: 2rem;
margin-block-end

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/app.module.ts
> +import {AppRoutingModule} from './app-routing.module';
فاصله اضافی پاک شود

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/banner/banner.component.scss
> +}
بهتره از امکانات nested که scss داره استفاده کنید

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/banner/banner.component.spec.ts
> +import {BannerComponent} from './banner.component';
فاصله اضافی

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/footer/footer.component.spec.ts
> +import {FooterComponent} from './footer.component';
فاصله اضافی

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/header/components/first-navbar/first-navbar.component.html
> +        <app-search-box></app-search-box>
یه خط فاصله به نظرم کافیه

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/header/components/hero/game-slider/game-slider.component.spec.ts
> +import {GameSliderComponent} from './game-slider.component';
باز همون قضیه فاصله

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/header/components/hero/hero.component.spec.ts
> +import {HeroComponent} from './hero.component';
باز همون

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/header/components/search-box/search-box.component.spec.ts
> +import {SearchBoxComponent} from './search-box.component';
فاصله. البته نمیدونم چرا ولی برای ماهم همینجوریه، منتور ما که سر این گیر میده

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/header/components/second-navbar/second-navbar.component.spec.ts
> +import {SecondNavbarComponent} from './second-navbar.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/header/header.component.spec.ts
> +import {HeaderComponent} from './header.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/header/header.module.ts
> +import {HeaderComponent} from './header.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/icon/icon.component.spec.ts
> +import {IconComponent} from './icon.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/main-cards/main-cards.component.spec.ts
> +import {MainCardsComponent} from './main-cards.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/main/components/slider-section/slider-section.component.spec.ts
> +import {SliderSectionComponent} from './slider-section.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/main/main.component.spec.ts
> +import {MainComponent} from './main.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/more-button/more-button.component.spec.ts
> +import {MoreButtonComponent} from './more-button.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/primary-title/primary-title.component.spec.ts
> +import {PrimaryTitleComponent} from './primary-title.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/components/slidebar/slidebar.component.spec.ts
> +import {SlidebarComponent} from './slidebar.component';
.

2022-07-24 12:08 UTC, Alirezab-2000 commented on src/app/pages/not-found/not-found.component.spec.ts
> +import {NotFoundComponent} from './not-found.component';
.

2022-07-24 12:22 UTC, Alirezab-2000 approved these changes

2022-07-24 12:22 UTC, AtaReversei approved these changes

2022-07-24 14:33 UTC, BijanEisapour requested changes

2022-07-24 14:33 UTC, BijanEisapour commented on README.md
> +برای همکاری به فایل CONTRIBUTING.md مراجعه کنید.
بعد اصن این فایل رو که نساختید

2022-07-24 14:33 UTC, BijanEisapour commented on .eslintrc.json
> +                        "prefix": ["app", "icon", "illustration"],
واقعاً از اینا استفاده کردید؟

2022-07-24 14:33 UTC, BijanEisapour commented on .github/workflows/deploy.yml
> +jobs:
جاب تست کو؟

2022-07-24 14:33 UTC, BijanEisapour commented on .prettierrc.json
> +}
این فایل آپدیت نیست 
از روی فاز 2 آپدیتش کنید

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/banner/banner.component.html
> +        <img src="assets/images/banner.webp" alt="بنر بزرگ" />
باید چیزی که تو عکس دیده میشه رو توصیف کنید 
نه اینکه صرفاً بگید بنر بزرگه

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/banner/banner.component.scss
> +.wrapper {
چرا stylelint ندارید؟

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/banner/banner.component.ts
> +    @Input() public bgColor: string = '';
اسم بهتر بذارید 
backgroundColorClassName

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/footer/footer.component.scss
> +    border-top: 1px solid hsl(0, 0%, 100%);
unit

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/header/components/hero/game-slider/game-slider.component.html
> +        <h2>the witcher</h2>
Title Case

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/header/components/hero/game-slider/game-slider.component.scss
> +            cursor: pointer;
به‌صورت پیش‌فرض هست

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/header/components/hero/hero.component.html
> +        <img src="assets/images/header-controller.png" alt="دسته بازی" />
اینایی که صرفاً جنبۀ زیبایی دارن رو alt خالی بذارید

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/header/components/search-box/search-box.component.scss
> +            border-bottom: 2px solid var(--input-color);
unit
دیگه نمیگم

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/main-cards/main-cards.component.ts
> +    ngOnInit(): void {}
x

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/main-cards/sample-data.ts
> +    {oldPrice: '60000', newPrice: '46000', imageUrl: 'assets/images/card1.webp'},
60_000
46_000

دیگه نمیگم

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/main/components/slider-section/slider-section.component.scss
> +        flex: 0 0 calc((100% / 4) - 1.5rem);
خب مگه نمیدونی 100 تقسیم بر 4 چند میشه؟
چرا مستقیم محاسبه‌ش نکردی؟

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/main/components/slider-section/slider-section.component.scss
> +        flex: 0 0 calc((100% / 3) - 1.5rem) !important;
وقتی important میذاری یعنی یه جای کار میلنگه 
اگه این شکلی بنویسی دیگه نیازی بهش نداری ... 
```scss
@media screen and (max-width: 75rem) {
    .slider {
          app-slider-card {
              flex: 0 0 calc((100% / 3) - 1.5rem) !important;
         }
    }
}
```

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/main/components/slider-section/slider-section.component.scss
> +        flex: 0 0 calc((100% / 2) - 1.5rem) !important;
به جای اینکه یه فرمول رو هر بار تکرار کنی، از custom property استفاده کن 
```css
--some-name: 4;

flex: 0 0 calc((100% / var(--some-name)) - 1.5rem);

.chiz {
    ---some-name: 3;
}
```

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/main/components/slider-section/slider-section.component.scss
> +@media screen and (max-width: 41rem) {
از پیکسل استفاده کن که آدم بفهمه دقیقاً چه سایزی منظورته 
اینجوری من باید 41 رو ضربدر 16 کنم

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/slidebar/slidebar.component.scss
> +    -webkit-box-pack: center;
از vendor prefix استفاده نکنید
دیگه نمیگم

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/slidebar/slidebar.component.scss
> +    height: 27rem !important;
اولاً کلاً height مطلق ندید 
ثانیاً important استفاده نکنید

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/slidebar/slidebar.component.ts
> +// install Swiper modules
x

2022-07-24 14:33 UTC, BijanEisapour commented on src/app/components/slidebar/slidebar.component.ts
> +// install Swiper modules
^

2022-07-24 14:33 UTC, BijanEisapour commented on src/assets/logos/seeto.svg
> +<svg width="99" height="92" viewBox="0 0 99 92" fill="none" xmlns="http://www.w3.org/2000/svg">
این چیه؟
جایی استفاده شده؟

2022-07-24 18:19 UTC, BijanEisapour approved these changes

2022-07-24 20:00 UTC, merged