Phase03
Star-Academy/Summer1401-FE-Team06 pull request #3
Opened 2022-08-02 09:59 UTC by AliZoghi

2022-08-02 10:17 UTC, Negarnbkhti42 requested changes

2022-08-02 10:17 UTC, Negarnbkhti42 commented on src/app/app.component.scss
> +    max-width: 1400px;
استفاده از logical properties

2022-08-02 10:17 UTC, Negarnbkhti42 commented on src/app/components/banner/banner.component.html
> +        <img src="assets/images/b1.webp" alt="مجموعه ای از عکس بازی های برتر"/>
ظاهرا چند تا عکس jpg دارید که استفاده نشدن. یا حذف بشن یا در صورت استفاده فرمت همه باید webp باشه

2022-08-02 10:17 UTC, Negarnbkhti42 commented on src/app/components/banner/banner.component.scss
> +    width: 100%;
گفته شد

2022-08-02 10:17 UTC, Negarnbkhti42 commented on src/app/components/banner/banner.component.scss
>      transition: transform 300ms;
بهتره از ثانیه استفاده بشه

2022-08-02 10:17 UTC, Negarnbkhti42 commented on src/app/components/header/components/second-navbar/second-navbar.component.scss
> +            border: 1px solid var(--secondary-color);
جز در صورت لزوم از rem استفاده بشه

2022-08-02 10:17 UTC, Negarnbkhti42 commented on src/app/components/header/components/second-navbar/second-navbar.component.spec.ts
> +    // let component: SecondNavbarComponent;
کامنت در کد نباشه

2022-08-02 10:47 UTC, msrazavi requested changes
همه عکس‌ها webp باشد.

2022-08-02 10:47 UTC, msrazavi commented on src/app/app.component.scss
> +    max-width: 1400px;
logical

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/banner/banner.component.html
> +        <img src="assets/images/b1.webp" alt="مجموعه ای از عکس بازی های برتر"/>
نیم‌فاصله

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/banner/banner.component.html
> -            <a routerLink="/">محصولات بیشتر</a>
نیم‌فاصله

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/banner/banner.component.scss
> +    width: 30rem;
logical

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/container/container.component.scss
> +    width: calc(100vw - 4rem);
logical

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/header/components/second-navbar/second-navbar.component.html
>              <li><a routerLink="#">بازی ها</a></li>
نیم‌فاصله

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/icon/icon.component.scss
>      height: 2rem;
گفته شد

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/icon/icon.component.scss
> +        height: auto;
گفته شد

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/main-cards/main-cards.component.html
> +    <app-primary-title title="بازی ها"></app-primary-title>
گفته شد

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/main-cards/main-cards.component.scss
> +    padding-bottom: 3rem;
logical

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/main-cards/main-cards.component.spec.ts
> +        //}
کامنت

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/main/components/slider-section/slider-section.component.scss
> +            flex: 0 0 300px;
پیکسل

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/main/components/slider-section/slider-section.component.scss
> +                height: 2rem;
گفته شد

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/main/main.component.html
> +        primaryTitle="پر فروش ترین بازی ها"
پرفروش‌ترین بازی‌ها

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/section/section.component.scss
> +    width: calc(100% + var(--space-need));
گفته شد

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/slidebar/slidebar.component.html
> +        <li><img src="assets/images/slider1.webp" alt="" /></li>
alt

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/slidebar/slidebar.component.scss
> +      height: 5rem;
یه replace all رو همه width و height ها بزنید :))

2022-08-02 10:47 UTC, msrazavi commented on src/app/components/slidebar/slidebar.component.ts
> +    public readonly INTERVAL_DELAY: number = 3000;
3_000

2022-08-02 10:47 UTC, msrazavi commented on src/app/enum/icon-type.enum.ts
> +    PRICE = 'fa-light fa-circle-dollar',
همه جا از fa-light استفاده شده؟

2022-08-02 10:47 UTC, msrazavi commented on src/app/services/api.service.ts
> +
کامنت

2022-08-02 10:47 UTC, msrazavi commented on src/app/services/auth.service.ts
> +    ///////////
گفته شد

2022-08-02 11:02 UTC, AtaReversei approved these changes

2022-08-02 11:02 UTC, AtaReversei commented on src/app/services/auth.service.spec.ts
> +    it('tests token - empty', () => {
tests یا should تو این فایل هم نگاه کنین

2022-08-02 11:02 UTC, dibaaamir requested changes

2022-08-02 11:02 UTC, dibaaamir commented on src/app/components/main/main.component.html
> +    <app-section primaryTitle="بازی های جنگی" [titleDirection]="titleDirectionType.LEFT" placeComponent="right-out">
نیم فاصله

2022-08-02 11:02 UTC, dibaaamir commented on src/app/components/section/section.component.scss
> +            width: 100%;
logical

2022-08-02 11:02 UTC, dibaaamir commented on src/app/components/slidebar/slidebar.component.scss
> +  width: 100%;
logical

2022-08-02 11:06 UTC, dibaaamir requested changes

2022-08-02 11:06 UTC, dibaaamir commented on src/styles.scss
> +    --clr-icon-white: hsl(0deg 0% 88%);
بهتره که برای border radius هم یکی یا دوتا درست کنین و یکسان بدین

2022-08-02 11:09 UTC, Alirezab-2000 commented on src/app/components/slidebar/slidebar.component.scss
> +      transition: transform 0.5s ease-in-out;
ترجیحا یه واحد استفاده کنید. بالاتر دیدم میلی ثانیه بود. یا اونا رو ثانیه کنید یا این رو میلی ثانیه

2022-08-02 11:09 UTC, Alirezab-2000 commented on src/app/components/section/section.component.scss
> +    box-shadow: 0 0 20px 0 hsl(0deg 0% 0% / 30%);
اینم همون قضیه واحد هاست که تبدیل به rem بشه در صورت امکان. پایینتر نمیگم

2022-08-02 11:09 UTC, Alirezab-2000 commented on src/app/services/api.service.ts
> +//
این کامنتا رو هم پاک کنید

2022-08-02 11:09 UTC, Alirezab-2000 commented on src/app/services/auth.service.ts
> +    //     const data = (await this.apiService.post<IdObject>(API_USER_AUTH, {token})) as IdObject;
همون قضیه کامنت اضافی

2022-08-02 11:18 UTC, dibaaamir requested changes

2022-08-02 11:18 UTC, dibaaamir commented on src/app/components/banner/banner.component.scss
> +  gap: 3.75rem;
خیلی اعشاری شده سعی کنید اعداد ساده تر بدین

2022-08-02 11:18 UTC, dibaaamir commented on src/app/components/slider-card/slider-card.component.scss
>      width: 100%;
logical

2022-08-02 11:18 UTC, dibaaamir commented on src/app/pages/auth/auth.component.scss
> +    min-height: 100vh;
logical

2022-08-02 11:21 UTC, dorrin-sot requested changes

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/banner/banner.component.ts
>  export class BannerComponent {
چسب :)

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/header/components/first-navbar/first-navbar.component.spec.ts
> +    it('should have container', () => {
^

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/header/components/search-box/search-box.component.spec.ts
> +    it('should have value input - with value', () => {
دوباره ^

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/header/components/second-navbar/second-navbar.component.scss
>                  &:hover {
این رو میتونین بنویسین &:hover a بعد خط پایینشو حذف کنین

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/icon/icon.component.spec.ts
> +    it('should render icon - icon Type - default', () => {
این چهار تا میتونن for باشن

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/icon/icon.component.spec.ts
> +    it('should render icon - icon color - default', () => {
اینجا هم همینطور (for)

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/icon/icon.component.spec.ts
> +        if (haveBg !== undefined) {
!!haveBg

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/main-cards/main-cards.component.spec.ts
> +    it('tests - cards', () => {
اسم تست ها همش یا با should شروع شه یا tests

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/header/components/search-box/search-box.component.html
>      <i class="far fa-magnifying-glass"></i>
همه آیکون‌ها یا باید regular باشن یا solid. فرمتشون یا همه حالت far/fas (کوتاه) باشه یا fa-regular/fa-solid (بلند)

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/main/components/slider-section/slider-section.component.spec.ts
> +    it('should slider element - scroll - right ', () => {
میتونه for باشه

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/main/components/slider-section/slider-section.component.spec.ts
> +        if (data !== undefined) {
!!data

2022-08-02 11:21 UTC, dorrin-sot commented on src/app/components/primary-title/primary-title.component.spec.ts
> +    it('should render - title direction - default', () => {
for

2022-08-02 11:26 UTC, msrazavi approved these changes

2022-08-06 15:07 UTC, AliZoghi commented on src/app/enum/icon-type.enum.ts
> +    PRICE = 'fa-light fa-circle-dollar',
خیر، ولی جوری بکار رفته که به ظاهر سایت لطمه وارد نکنه.

2022-08-06 15:17 UTC, AliZoghi commented on src/app/components/footer/footer.component.html
>              <a href="#"><i class="fa-brands fa-youtube"></i></a>
لینک داخلی نیست

2022-08-06 15:22 UTC, AliZoghi commented on src/app/components/icon/icon.component.spec.ts
> +    //  Icon color test
به دلیل مربوط بودن تستا اینکارو کردیم تا منظم تر به چشم بخورن.

2022-08-06 15:27 UTC, AliZoghi commented on src/app/components/section/section.component.scss
> +    box-shadow: 0 0 20px 0 hsl(0deg 0% 0% / 30%);
box-shadow هارو مقدار پیکسل دادیم

2022-08-06 15:32 UTC, AliZoghi commented on src/app/components/icon/icon.component.spec.ts
> +        if (haveBg !== undefined) {
اینطوری مقدار false رو وارد شرط if نمیکنه

2022-08-06 19:31 UTC, dibaaamir approved these changes

2022-08-06 19:35 UTC, Negarnbkhti42 approved these changes

2022-08-07 14:16 UTC, Alirezab-2000 approved these changes

2022-08-08 15:46 UTC, dorrin-sot approved these changes

2022-08-09 06:22 UTC, milar7 requested changes
code -coverage تو تمام معیارهای Lines و Branches و Statements و Functions و ... باید حداقل 80درصد رو داشته باشه

2022-08-09 15:03 UTC, BijanEisapour approved these changes

2022-08-09 15:03 UTC, BijanEisapour commented on src/app/components/more-button/more-button.component.spec.ts
> +        const buttonContainerEl = host.querySelector('.more');
^

2022-08-09 15:03 UTC, BijanEisapour commented on src/app/components/more-button/more-button.component.spec.ts
> +        if (isReverse) {
^

2022-08-09 15:03 UTC, BijanEisapour commented on src/app/components/primary-title/primary-title.component.spec.ts
> +    const testTitleDirection = (direction?: PrimaryTitleDirection): void => {
^

2022-08-09 15:03 UTC, BijanEisapour commented on src/app/components/section/section.component.scss
> +@media screen and (max-width: 1450px) {
^

2022-08-09 15:03 UTC, BijanEisapour commented on src/app/components/section/section.component.spec.ts
> +    const testHavePrimaryTitle = (haveTitle: boolean): void => {
^

2022-08-09 15:38 UTC, milar7 approved these changes

2022-08-09 15:39 UTC, merged